SELECT a.ANIMAL_ID, a.NAME
FROM (
    SELECT ai.ANIMAL_ID, ai.NAME, ai.DATETIME, ao.DATETIME AS OUTCOME_DATETIME,
           DATEDIFF(ao.DATETIME, ai.DATETIME) AS PROTECTION_PERIOD
    FROM ANIMAL_INS ai
    JOIN ANIMAL_OUTS ao ON ai.ANIMAL_ID = ao.ANIMAL_ID
) AS a
ORDER BY a.PROTECTION_PERIOD DESC
LIMIT 2;