SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A
JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
HAVING A.FAVORITES = (SELECT MAX(A1.FAVORITES) 
                     FROM REST_INFO A1 
                     WHERE A1.ADDRESS LIKE '서울%' 
                     AND A1.REST_ID = A.REST_ID)
ORDER BY SCORE DESC, A.FAVORITES DESC;