WITH MAX_SIZE_OF_COLONY_PER_YEAR AS (
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR
),
ECOLI_YEAR_DATA AS (
    SELECT 
        ed.ID,
        EXTRACT(YEAR FROM ed.DIFFERENTIATION_DATE) AS YEAR,
        MAX_SIZE_OF_COLONY - ed.SIZE_OF_COLONY AS YEAR_DEV
    FROM 
        ECOLI_DATA ed
    INNER JOIN 
        MAX_SIZE_OF_COLONY_PER_YEAR msocpy
    ON 
        EXTRACT(YEAR FROM ed.DIFFERENTIATION_DATE) = msocpy.YEAR
)
SELECT 
    YEAR,
    YEAR_DEV,
    ID
FROM 
    ECOLI_YEAR_DATA
ORDER BY 
    YEAR ASC,
    YEAR_DEV ASC;