SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS max_length
    FROM FISH_INFO
    WHERE LENGTH > 10
    GROUP BY FISH_TYPE
) max_length_info
JOIN FISH_INFO FI ON max_length_info.FISH_TYPE = FI.FISH_TYPE AND max_length_info.max_length = FI.LENGTH
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID ASC;